
// This file has been generated by the GUI designer. Do not modify.
namespace Serpis.ed
{
	public partial class ArrayButton
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Serpis.ed.ArrayButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Serpis.ed.ArrayButton";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
