
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label1;
	private global::Gtk.Entry entry1;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label2;
	private global::Gtk.Entry entry2;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label3;
	private global::Gtk.Entry entryResult;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button BotonSuma;
	private global::Gtk.Button BotonResta;
	private global::Gtk.Button BotonMulti;
	private global::Gtk.Button BotonDiv;
	private global::Gtk.Button BotonReset;
	private global::Gtk.Table table1;
	private global::Gtk.Button dos;
	private global::Gtk.Button tres;
	private global::Gtk.Button uno;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Valor1");
		this.hbox3.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.hbox3.Add (this.entry1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry1]));
		w2.Position = 1;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Valor2");
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w4.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.hbox4.Add (this.entry2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entry2]));
		w5.Position = 1;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Result");
		this.hbox5.Add (this.label3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
		w7.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entryResult = new global::Gtk.Entry ();
		this.entryResult.CanFocus = true;
		this.entryResult.Name = "entryResult";
		this.entryResult.IsEditable = true;
		this.entryResult.InvisibleChar = '•';
		this.hbox5.Add (this.entryResult);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryResult]));
		w8.Position = 1;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BotonSuma = new global::Gtk.Button ();
		this.BotonSuma.CanFocus = true;
		this.BotonSuma.Name = "BotonSuma";
		this.BotonSuma.UseUnderline = true;
		// Container child BotonSuma.Gtk.Container+ContainerChild
		global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w11 = new global::Gtk.HBox ();
		w11.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w12 = new global::Gtk.Image ();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w11.Add (w12);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w14 = new global::Gtk.Label ();
		w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Suma");
		w14.UseUnderline = true;
		w11.Add (w14);
		w10.Add (w11);
		this.BotonSuma.Add (w10);
		this.hbox2.Add (this.BotonSuma);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BotonSuma]));
		w18.Position = 0;
		w18.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BotonResta = new global::Gtk.Button ();
		this.BotonResta.CanFocus = true;
		this.BotonResta.Name = "BotonResta";
		this.BotonResta.UseUnderline = true;
		// Container child BotonResta.Gtk.Container+ContainerChild
		global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w20 = new global::Gtk.HBox ();
		w20.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w21 = new global::Gtk.Image ();
		w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
		w20.Add (w21);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w23 = new global::Gtk.Label ();
		w23.LabelProp = global::Mono.Unix.Catalog.GetString ("Resta");
		w23.UseUnderline = true;
		w20.Add (w23);
		w19.Add (w20);
		this.BotonResta.Add (w19);
		this.hbox2.Add (this.BotonResta);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BotonResta]));
		w27.Position = 1;
		w27.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BotonMulti = new global::Gtk.Button ();
		this.BotonMulti.CanFocus = true;
		this.BotonMulti.Name = "BotonMulti";
		this.BotonMulti.UseUnderline = true;
		// Container child BotonMulti.Gtk.Container+ContainerChild
		global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w29 = new global::Gtk.HBox ();
		w29.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w30 = new global::Gtk.Image ();
		w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
		w29.Add (w30);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w32 = new global::Gtk.Label ();
		w32.LabelProp = global::Mono.Unix.Catalog.GetString ("Multi");
		w32.UseUnderline = true;
		w29.Add (w32);
		w28.Add (w29);
		this.BotonMulti.Add (w28);
		this.hbox2.Add (this.BotonMulti);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BotonMulti]));
		w36.Position = 2;
		w36.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BotonDiv = new global::Gtk.Button ();
		this.BotonDiv.CanFocus = true;
		this.BotonDiv.Name = "BotonDiv";
		this.BotonDiv.UseUnderline = true;
		// Container child BotonDiv.Gtk.Container+ContainerChild
		global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w38 = new global::Gtk.HBox ();
		w38.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w39 = new global::Gtk.Image ();
		w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_edit", global::Gtk.IconSize.Menu);
		w38.Add (w39);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w41 = new global::Gtk.Label ();
		w41.LabelProp = global::Mono.Unix.Catalog.GetString ("Division");
		w41.UseUnderline = true;
		w38.Add (w41);
		w37.Add (w38);
		this.BotonDiv.Add (w37);
		this.hbox2.Add (this.BotonDiv);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BotonDiv]));
		w45.Position = 3;
		w45.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BotonReset = new global::Gtk.Button ();
		this.BotonReset.CanFocus = true;
		this.BotonReset.Name = "BotonReset";
		this.BotonReset.UseUnderline = true;
		this.BotonReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.hbox2.Add (this.BotonReset);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BotonReset]));
		w46.Position = 4;
		w46.Fill = false;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w47.Position = 3;
		w47.Expand = false;
		w47.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.dos = new global::Gtk.Button ();
		this.dos.CanFocus = true;
		this.dos.Name = "dos";
		this.dos.UseUnderline = true;
		this.dos.FocusOnClick = false;
		this.dos.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.table1.Add (this.dos);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1 [this.dos]));
		w48.LeftAttach = ((uint)(1));
		w48.RightAttach = ((uint)(2));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tres = new global::Gtk.Button ();
		this.tres.CanFocus = true;
		this.tres.Name = "tres";
		this.tres.UseUnderline = true;
		this.tres.FocusOnClick = false;
		this.tres.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.table1.Add (this.tres);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1 [this.tres]));
		w49.LeftAttach = ((uint)(2));
		w49.RightAttach = ((uint)(3));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.uno = new global::Gtk.Button ();
		this.uno.CanFocus = true;
		this.uno.Name = "uno";
		this.uno.UseUnderline = true;
		this.uno.FocusOnClick = false;
		this.uno.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.table1.Add (this.uno);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1 [this.uno]));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox3.Add (this.table1);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table1]));
		w51.PackType = ((global::Gtk.PackType)(1));
		w51.Position = 4;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 417;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
